# Generated by Django 4.1.3 on 2022-12-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='State',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='zip',
            field=models.IntegerField(default='99999'),
        ),
    ]
