# Generated by Django 4.1.3 on 2022-12-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='Include a description of condition and other relevant information...'),
        ),
        migrations.AlterField(
            model_name='game',
            name='console',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='factory_sealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(default='Only include title please', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='version',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.DateField(),
        ),
    ]
