# Generated by Django 4.1.4 on 2023-01-04 20:30

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_rename_image_game_image1_game_image2_game_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=games.models.upload_path),
        ),
        migrations.AlterField(
            model_name='game',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=games.models.upload_path),
        ),
        migrations.AlterField(
            model_name='game',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=games.models.upload_path),
        ),
        migrations.AlterField(
            model_name='game',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=games.models.upload_path),
        ),
        migrations.AlterField(
            model_name='game',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=games.models.upload_path),
        ),
    ]
