# Generated by Django 4.1.4 on 2023-01-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_image1_alter_game_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='game',
            name='factory_sealed',
        ),
        migrations.RemoveField(
            model_name='game',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='image5',
        ),
    ]
